<div id="menu_listas">
    <a href="lista_config_<?=$attrs['ID_HISTORICO_GERADOC']?>">Configurações</a>
</div>
<div id="lista_config_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="opt_lista">
    <!-- Opções de Configuração da Lista -->
    <table class="table_opts_lista">
        <tr>
            <td colspan="2" style="background-color:#EDEDED;">
                <!-- Informações da Lista -->
                <table class="table_info_lista">
                    <tr>
                        <td width="33%" nowrap="nowrap">
                            <strong>
                                Nome da Lista
                            </strong>
                            <br />
                            <?=$attrs['NOME_ARQ']?>
                        </td>
                        <td width="33%" nowrap="nowrap">
                            <strong>
                                Código da Lista
                            </strong>
                            <br />
                            <?=$attrs['COD_LISTA']?>
                        </td>
                        <td width="33%" nowrap="nowrap">
                            <strong>
                                Status
                            </strong>
                            <br />
                            <? 
                                if($attrs['STATUS'] == 'Ativa'){ 
                                    $cor = 'green';
                                }else{
                                    $cor = 'red';
                                }
                            ?>
                            <strong style="color:<?=$cor?>;">
                                <?=$attrs['STATUS']?>
                            </strong>
                        </td>
                    </tr>
                </table>
                <!-- Informações da Lista -->
            </td>
        </tr>
        <tr>
            <td>
                <strong>Anticola</strong>
                <br />
                <span>Opção utilizada para dificultar a cola dos alunos.</span>
            </td>
            <td>
                <strong>Status</strong>
                <br />
                <input type="radio" name="anticola_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="1" onclick="javascript:alteraAnticola(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ANTICOLA'] == 1 ? 'checked="checked"' : '' ?> /> Habilitada
                &nbsp;
                <input type="radio" name="anticola_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="0" onclick="javascript:alteraAnticola(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ANTICOLA'] == 0 ? 'checked="checked"' : '' ?> /> Desabilitada
            </td>
        </tr>
        <tr>
            <td>
                <strong>Período</strong>
                <br />
                <span>Determina o período de validade da lista, entre uma data inicial e uma final.</span>
            </td>
            <td>
                <div style="float:left;">
                    <strong>Início</strong>
                    <br />
                    <input type="text" id="periodo_inicio_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="periodo_inicio_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="periodo_ini periodo" value="<?=$attrs['PERIODO_INICIO']?>" onchange="alteraPeriodo(this.value, 'INI', <?=$attrs['ID_HISTORICO_GERADOC']?>);" />
                </div>
                <div>
                    <strong>Final</strong>
                    <br />
                    <input type="text" id="periodo_final_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="periodo_final_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="periodo_fim periodo" value="<?=$attrs['PERIODO_FINAL']?>" onchange="alteraPeriodo(this.value, 'FIM', <?=$attrs['ID_HISTORICO_GERADOC']?>);" />
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <strong>Resultado do Aluno</strong>
                <br />
                <span>Opção utilizada para exibir resultado final ao aluno.</span>
            </td>
            <td>
                <strong>Status</strong>
                <br />
                <input type="radio" name="resultado_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="1" onclick="javascript:alteraResultadoAluno(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ST_RESULTADO_ALUNO'] == 1 ? 'checked="checked"' : '' ?> /> Habilitado
                &nbsp;
                <input type="radio" name="resultado_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="0" onclick="javascript:alteraResultadoAluno(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ST_RESULTADO_ALUNO'] == 0 ? 'checked="checked"' : '' ?> /> Desabilitado
            </td>
        </tr>
        <tr>
            <td>
                <strong>Gabarito</strong>
                <br />
                <span>Opção utilizada para exibir, ou não, o Gabarito ao aluno.</span>
            </td>
            <td>
                <strong>Status</strong>
                <br />
                <input type="radio" name="gabarito_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="1" onclick="javascript:alteraGabaritoAluno(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ST_GABARITO_ALUNO'] == 1 ? 'checked="checked"' : '' ?> /> Habilitado
                &nbsp;
                <input type="radio" name="gabarito_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="0" onclick="javascript:alteraGabaritoAluno(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ST_GABARITO_ALUNO'] == 0 ? 'checked="checked"' : '' ?> /> Desabilitado
            </td>
        </tr>
        <tr>
            <td>
                <strong>Tempo de Vida</strong>
                <br />
                <span>
                    Determina o tempo (em horas e minutos) que o Aluno possui para iniciar e finalizar a lista. Ex: 00:30 (Meia hora)
                    <br />
                    Caso o tempo seja 00:00 o Aluno poderá finalizar a lista no tempo necessário para ele, sem limite.
                </span>
            </td>
            <td>
                <strong>Tempo</strong>
                <br />
                <input type="text" id="tempo_vida_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="tempo_vida_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="tempo_vida" value="<?=$attrs['TEMPO_VIDA']?>" onkeyup="alteraTempoVida(this.value, <?=$attrs['ID_HISTORICO_GERADOC']?>);" onchange="alteraTempoVida(this.value, <?=$attrs['ID_HISTORICO_GERADOC']?>);" />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <strong>Números da Lista</strong>                
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <!-- Gráficos e Dados -->
                <div id="gr_respostas_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="gr_config_lista">
                    <p>
                        Respostas
                        <br />
                        <strong>0</strong>
                    </p>
                </div>
                <div id="gr_alunos_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="gr_config_lista">
                    <p>
                        Alunos
                        <br />
                        <strong>0</strong>
                    </p>
                </div>
                <div id="aproveitamento_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="gr_config_lista">
                    <p>
                        Aproveitamento
                        <br />
                        <strong id="num_proveitamento_<?=$attrs['ID_HISTORICO_GERADOC']?>">0</strong>%
                    </p>
                </div>
                <!-- Gráficos e Dados -->                
            </td>
        </tr>
    </table>
    
    <!-- Opções de Configuração da Lista --> 
</div>