<div class="conteudo_abas">

   <div class="espaco"></div>

   <div id="nav">
    <ul class="button-bar">
        <li><a href="javascript:void(0);"><span class="icon" data-icon="u"></span> Navegue como Aluno</a></li>
        <li><a href="javascript:void(0);" onclick="javascript:menuLista('lista_config_<?=$attrs['ID_HISTORICO_GERADOC']?>');"><span class="icon" data-icon="z"></span> Configurações</a></li>
        <li><a href="javascript:void(0);" onclick="javascript:menuLista('lista_resultados_<?=$attrs['ID_HISTORICO_GERADOC']?>');"><span class="icon" data-icon="k"></span> Resultado</a></li>
        <li><a href="javascript:void(0);" onclick="javascript:menuLista('lista_alunos_<?=$attrs['ID_HISTORICO_GERADOC']?>');"><span class="icon" data-icon="k"></span> Alunos</a></li>
    </ul>
</div>
   
     <div class="espaco"></div>
   
<div id="lista_config_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="opt_lista <?=$attrs['ID_HISTORICO_GERADOC']?>">
<!-- Opções de Configuração da Lista -->
    <!-- Anticola -->
        <div class="col_8">  
            <h5>Anticola:</h5>
        </div>
        <div class="col_12">  
            <blockquote>Opção utilizada para dificultar a cola dos alunos.</blockquote>
        </div>
        <div class="col_2">
            <input type="radio" id="anti_habilitada" name="anticola_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="1" onclick="javascript:alteraAnticola(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ANTICOLA'] == 1 ? 'checked="checked"' : '' ?> /> 
            <label for="anti_habilitada" class="inline">Habilitada</label>
        </div>
        <div class="col_3">
            <input type="radio" id="anti_desabilitada" name="anticola_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="0" onclick="javascript:alteraAnticola(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ANTICOLA'] == 0 ? 'checked="checked"' : '' ?> /> 
            <label for="anti_desabilitada" class="inline">Desabilitada</label>
        </div>
        <hr class="alt1" />
    <!-- Anticola -->

    <!-- Espaçamento -->
        <div class="espaco"></div>
    <!-- fim Espaçamento -->

    <!-- Período -->
        <div class="col_6">  
            <h5>Período:</h5>
        </div>
        <div class="col_12">  
            <blockquote>Determina o período de validade da lista, entre uma data inicial e uma final.</blockquote>
        </div>     
        <div class="col_1">Início</div>
        <div class="col_3"><input type="text" placeholder="Início" id="periodo_inicio_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="periodo_inicio_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="periodo_ini periodo" value="<?=$attrs['PERIODO_INICIO']?>" onchange="alteraPeriodo(this.value, 'INI', <?=$attrs['ID_HISTORICO_GERADOC']?>);" />
        </div>
        <div class="col_1">Fim</div>
        <div class="col_2"><input type="text" placeholder="Fim" id="periodo_final_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="periodo_final_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="periodo_fim periodo" value="<?=$attrs['PERIODO_FINAL']?>" onchange="alteraPeriodo(this.value, 'FIM', <?=$attrs['ID_HISTORICO_GERADOC']?>);" />
        </div>
    <div class="espaco"></div>
        <hr class="alt1" />
    <!-- Período -->

    <!-- Espaçamento -->
        <div class="espaco"></div>
    <!-- fim Espaçamento -->

    <!-- Resultado Aluno -->
        <div class="col_8">  
            <h5>Resultado do aluno:</h5>
        </div>
        <div class="col_12">  
            <blockquote>Opção utilizada para exibir resultado final ao aluno.</blockquote>
        </div>
        <div class="col_2">
            <input type="radio" id="res_habilitado" name="resultado_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="1" onclick="javascript:alteraResultadoAluno(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ST_RESULTADO_ALUNO'] == 1 ? 'checked="checked"' : '' ?> />
            <label for="res_habilitado" class="inline">Habilitado</label>
        </div>
        <div class="col_3">
            <input type="radio" id="res_desabilitado" name="resultado_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="0" onclick="javascript:alteraResultadoAluno(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ST_RESULTADO_ALUNO'] == 0 ? 'checked="checked"' : '' ?> />
            <label for="res_desabilitado" class="inline">Desabilitado</label>
        </div>
        <hr class="alt1" />
    <!-- Resultado Aluno -->

    <!-- Espaçamento -->
        <div class="espaco"></div>
    <!-- fim Espaçamento -->

    <!-- Gabarito -->
        <div class="col_8">  
            <h5>Gabarito:</h5>
        </div>
        <div class="col_12">  
            <blockquote>Opção utilizada para exibir, ou não, o Gabarito ao aluno.</blockquote>
        </div>
        <div class="col_2">
            <input type="radio" id="gab_habilitado" name="gabarito_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="1" onclick="javascript:alteraGabaritoAluno(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ST_GABARITO_ALUNO'] == 1 ? 'checked="checked"' : '' ?> />
            <label for="gab_habilitado" class="inline">Habilitado</label>
        </div>
        <div class="col_3">
            <input type="radio" id="gab_desabilitado" name="gabarito_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="0" onclick="javascript:alteraGabaritoAluno(this.value, '<?=$attrs['ID_HISTORICO_GERADOC']?>');" <?=$attrs['ST_GABARITO_ALUNO'] == 0 ? 'checked="checked"' : '' ?> />
            <label for="gab_desabilitado" class="inline">Desabilitado</label>
        </div>
        <hr class="alt1" />
    <!-- Gabarito -->

    <!-- Espaçamento -->
        <div class="espaco"></div>
    <!-- fim Espaçamento -->

    <!-- Tempo de Vida -->
        <div class="col_8">  
            <h5>Tempo de Vida:</h5>
        </div>
        <div class="col_12">  
            <blockquote>Determina o tempo (em horas e minutos) que o Aluno possui para iniciar e finalizar a lista.<p>Ex: 00:30 (Meia hora)</p>
            <br />
            Caso o tempo seja 00:00 o Aluno poderá finalizar a lista no tempo necessário para ele, sem limite.</blockquote>
        </div>
        <div class="col_12"> 
            <div class="col_1">
                <h5>Tempo</h5></div>
                &nbsp;
                <div class="col_2"><input type="text" id="tempo_vida_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="tempo_vida_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="tempo_vida" value="<?=$attrs['TEMPO_VIDA']?>" onkeyup="alteraTempoVida(this.value, <?=$attrs['ID_HISTORICO_GERADOC']?>);" onchange="alteraTempoVida(this.value, <?=$attrs['ID_HISTORICO_GERADOC']?>);" />
            </div>
        </div>
            <div class="linha"></div>
    <!-- Tempo de Vida -->
<div class="espaco"></div>
<div class="espaco"></div>
    <!-- Opções de Configuração da Lista --> 
</div>

<div id="lista_resultados_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="opt_lista <?=$attrs['ID_HISTORICO_GERADOC']?>" style="display:none;">
<!-- Resultados da Lista -->
    <table class="tb_resultados_listas">
  <tr>
    <td colspan="4">
        <h6>Escola</h6>
        <select id="escolas_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="escolas_<?=$attrs['ID_HISTORICO_GERADOC']?>" onchange="javascript:filtrosResultados(<?=$attrs['ID_HISTORICO_GERADOC']?>);"></select>
    </td>
  </tr>
  <tr>
    <td>
        <h6>Ensino</h6>
        <select id="ensino_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="ensino_<?=$attrs['ID_HISTORICO_GERADOC']?>" multiple="multiple" onchange="javascript:filtrosResultados(<?=$attrs['ID_HISTORICO_GERADOC']?>);"></select>
    </td>
    <td>
        <h6>Período</h6>
        <select id="periodo_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="periodo_<?=$attrs['ID_HISTORICO_GERADOC']?>" multiple="multiple" onchange="javascript:filtrosResultados(<?=$attrs['ID_HISTORICO_GERADOC']?>);"></select>
    </td>
    <td>
        <h6>Ano</h6>
       <select id="ano_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="ano_<?=$attrs['ID_HISTORICO_GERADOC']?>" multiple="multiple" onchange="javascript:filtrosResultados(<?=$attrs['ID_HISTORICO_GERADOC']?>);"></select>
</td>
    <td>  <h6>Turmas</h6>
                <select id="turmas_<?=$attrs['ID_HISTORICO_GERADOC']?>" name="turmas_<?=$attrs['ID_HISTORICO_GERADOC']?>" multiple="multiple"></select>
</td>
  </tr>
  <tr>
    <td colspan="4"><input type="button" value="Filtrar" onclick="javascript:geraGrafico(<?=$attrs['ID_HISTORICO_GERADOC']?>);" /></td>
  </tr>
</table>

                <!-- Gráficos e Dados -->
                <div class="col_4">
                <div id="aproveitamento_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="gr_config_lista">
                    <p>
                        Aproveitamento
                        <br />
                        <span id="num_proveitamento_<?=$attrs['ID_HISTORICO_GERADOC']?>">0</span>%
                    </p>
                </div>
                </div>
                <div class="col_4">
                <div id="gr_respostas_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="gr_config_lista">
                    <p>
                        Respostas
                        <br />
                        <span>0</span>
                    </p>
                </div>
                </div>
                <div class="col_4">
                <div id="gr_alunos_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="gr_config_lista">
                    <p>
                        Alunos
                        <br />
                        <span>0</span>
                    </p>
                </div>
                </div>
                <!-- Gráficos e Dados --> 

                <!-- Gráficos Aproveitamento Questões -->
                <div class="col_12">
                <div id="gr_questoes_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="gr_config_lista" style="height:auto;">
                    <p>
                        Questões
                        <br />
                        <span>0</span>
                    </p>
                </div>
                </div>
                <div class="col_3">
               
                <!-- Gráficos Aproveitamento Questões --> 
                <input type="button" value="Gráfico Aluno x Universo" onclick="javascript:modalAluno(<?=$attrs['ID_HISTORICO_GERADOC']?>)" />
               
                </div>
                
                <div class="col_3">
                <!-- Gráficos Aluno x Universo -->
                <input type="button" value="Imprimir Gráficos" onclick="javascript:imprimirGraficos(<?=$attrs['ID_HISTORICO_GERADOC']?>)" />

                </div>
                
                
                <div class="col_4">
              
                <!-- Gráficos Aluno x Universo -->
                <div id="gr_aluno_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="gr_config_lista" style="display:none;height:310px;">&nbsp;</div>
                
                </div>
                
<!-- Resultados da Lista -->
</div>
     <div class="col_12">
         <div id="grid_alunos">
<div id="lista_alunos_<?=$attrs['ID_HISTORICO_GERADOC']?>" class="opt_lista <?=$attrs['ID_HISTORICO_GERADOC']?>" style="display:none;">
    <table id="grid_alunos_status_<?=$attrs['ID_HISTORICO_GERADOC']?>" style="width:100%;"></table>
    <div id="pg_alunos_status_<?=$attrs['ID_HISTORICO_GERADOC']?>"></div>
</div>

<div id="modal_alunos_<?=$attrs['ID_HISTORICO_GERADOC']?>" style="display:none;">
    <table id="grid_alunos_<?=$attrs['ID_HISTORICO_GERADOC']?>" style="width:100%;"></table>
    <div id="pg_alunos_<?=$attrs['ID_HISTORICO_GERADOC']?>"></div>
    <input type="hidden" id="tmp_aproveitamento_<?=$attrs['ID_HISTORICO_GERADOC']?>" value="10" />
</div>
         </div>
     </div>
</div>
<div class="espaco"></div>