<!--
    Menu vertical da área Admin:
    O css de formatação encontra-se no arquivo assets/css/admin/menuVertical.css
-->
<div id='menu'><p>Titulo</p></div>
<ul class='sub-menu'>
    <?php 
        foreach($itens as $arrItem){            
            $cls        = $arrItem['CLS'];
            $id         = $cls;
            $link       = $arrItem['LINK'];
            $text       = $arrItem['TEXT'];
            $selected   = (int)$arrItem['SELECTED'];
            $url        = $link.'/';
            //Verifica se o item atual deve aparecer como selecionado.
            $clsSel     = '';
            if ($selected == 1) $clsSel = $cls.'Sel Sel';
    ?>
        <li><a class='<?=$cls?> <?=$clsSel?>' href='<?=$url?>' id="<?=$id?>"><?=$text?></a></li>
    <?php } ?>
</ul>