<div id="nav">
    <ul class="menu">
        <li id="nav_1" class="first">
            <? foreach($itens as $item){ ?>
                <li <? if($item['ITEM'] == $itemSel){ ?> class="current" <? } ?>><a href="<?=$item['HREF']?>"><?=$item['TEXT']?></a></li>
            <? } ?>
        </li>
    </ul>	
    <a class="btn small blue" href="/downloads/"><span class="icon" data-icon="U"></span>Chat</a>
</div>