<div class="container">
    <!-- MODAL loginbox -->
    <a id="modal_loginbox" href="#mloginbox_div" style="display: none;"></a>
    <div id="mloginbox_div" style="width:400px;display:none;text-align:center">
        <table style="width:390px;height:120px;" align="center">
            <tr>
                <td align="center" valign="middle" style="width:100%;height:120px;vertical-align:middle;">
                    <!-- MSG -->
                    <table align="center">
                        <tr>
                            <td id="msg_loginbox" align="center" style="vertical-align:middle;padding:10px;font-weight:bold;font-size:16px;">
                                &nbsp;
                            </td>
                        </tr>
                    </table>
                    <!-- MSG -->
                </td>
            </tr>
        </table>
    </div>
    <!-- MODAL loginbox -->
    
    <div class="sub_top">
        <span>Fone: 11 3549-3988</span>
        <span><a href="chat.php">Atendimento on-line</a></span>
       
    </div>  
    <div id="idiomas">
        <select class="mydds" name="myimge">0
            <option value="pt" selected="selected" title="app/views/images/br.png">Português</option>
            <option value="en" title="app/views/images/usa.png">Inglês</option>
        </select>
    </div> 
    <div id="login2">
    <? 
            if(isset($_SESSION['user_site'])){ 
                $objUser = unserialize($_SESSION['user_site']);
        ?>
        Olá <a href="javascript:void(0);" onclick="javascript:site.boxUsuario();"><?=$objUser->NOME?>!</a>
        <? 
            }else{ 
                $objUser = null;
        ?>
        <a href="javascript:void(0);" onclick="javascript:site.boxUsuario();">LOGIN</a>
        <?
            }
        ?>
        &nbsp;&nbsp;&nbsp;
    </div>
    
    <? if($objUser == null){ ?>
    <!-- Login Usuário -->
    <div id="box_usuario" style="display:none;">
        <!-- Login Normal -->
        <div id="box_login" class="box_table">
            <form id="form_loginbox" name="form_loginbox" action="usuario/login" method="post" onSubmit="return form.validate(this, true, 'reloadPage');">
                <table>
                    <tr>
                        <td>
                            E-mail
                            <br />
                            <input type="text" id="login_email" name="login_email" value="Usuário" style="width:300px;" class="required email" field_name="E-mail" />
                        </td>
                        <td>
                            <br />
                            <a href="javascript:void(0);" title="Login com sua conta do Facebook" onclick="javascript:window.open('socialauth/facebook', 'Facebook', 'width=800,height=600');"><img src="app/views/images/icone_facebook.jpg" border="0" style="width:20px;height:20px;" /></a>
                            &nbsp;
                            <a href="javascript:void(0);" title="Login com sua conta do Google" onclick="javascript:window.open('socialauth/google', 'Google', 'width=800,height=600');"><img src="app/views/images/icone_google.gif" border="0" style="width:20px;height:20px;" /></a>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Senha
                            <br />
                            <input type="password" id="login_senha" name="login_senha" value="Senha" style="width:360px;" class="required" field_name="Senha" />
                        </td>
                    </tr>
                    <tr>
                        <td align="left" colspan="2">
                            <input type="submit" value="Login" class="bt_normal" />
                        </td>
                    </tr>
                    <tr>
                        <td align="left" colspan="2">
                            <input type="button" value="Esqueci minha senha" class="bt_normal" />
                        </td>
                    </tr>
                    <tr>
                        <td align="left" colspan="2">
                            <input type="button" value="Cadastre-se agora" class="bt_normal" />
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <!-- Login Normal -->
    </div>
    <!-- Login Usuário -->
    <? }else{ ?>
    <!-- Usuário Logado -->
    <div id="box_usuario" style="display:none;">
        <div>
            <ul>
                <li>
                    Alterar Plano
                </li>
                <li>
                    Alterar Dados
                </li>
                <li>
                    Alterar Senha
                </li>
                <li>
                    <a href="javascript:void(0)" onclick="javascript:site.logoff();">Sair</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- Usuário Logado -->
    <? } ?>
    
</div>
