<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>E-mail Contato</title>
    </head>
    <body>
        O usuário <?=self::$dadosEmail['nome']?> acaba se enviar a seguinte mensagem via Site:
        <br /><br />
        <i>
            "<?=self::$dadosEmail['msg']?>"
        </i>
        <br />
        <br />
        <strong>
            Tecnologia Interbits
            <br />
        </strong>
    </body>
</html>
