<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>E-mail Contato</title>
    </head>
    <body>
        Olá <?=self::$dadosEmail['nome']?>! Acabamos de receber sua mensagem:
        <br /><br />
        <i>
            "<?=self::$dadosEmail['msg']?>"
        </i>
        <br /><br />
        Aguarde... Dentro de 24 hs estaremos lhe enviando uma resposta no e-mail: <?=self::$dadosEmail['email']?>.
        <br /><br />
        <strong>
            Atenciosamente,
            <br />
            Equipe Interbits
            <br />
        </strong>
    </body>
</html>
