<!--<div class="top">
    <div class="container nav-wrap">
        <ul class="group" id="top-menu">
            <li id="menu_home" class="current_page_item" onclick="javascript:menu.changeMenu(this.id);">
                <a href="index.php?pg=home">Home<p>Bem Vindo</p></a>
            </li>
            <li id="menu_sobre" onclick="javascript:menu.changeMenu(this.id);">
                <a href="sobreNos">Sobre Nós<p>Conheça a InterBits</p></a>
            </li>
            <li id="menu_assine"  onclick="javascript:menu.changeMenu(this.id);">
                <a href="assineja.php?pg=assine">Assine Já<p>Planos & Preços</p></a>
            </li>
                <li id="menu_super"  onclick="javascript:menu.changeMenu(this.id);">
                <a href="super.php?pg=super">SuperPro<p>Principais Recursos</p></a>
            </li>
                <li id="menu_ajuda"  onclick="javascript:menu.changeMenu(this.id);">
                <a href="ajuda.php?pg=ajuda">Ajuda<p>FAQ e Tutoriais</p></a>
            </li>
        </ul>
    </div>            
</div>-->
<div class="top">
    <div class="container nav-wrap">
        <ul class="group" id="top-menu">
            <? foreach(self::$arrMenuOpts as $id => $menu){ ?>
            <li id="<?=$id?>" <? if($menu['ativo'] === TRUE){ ?> class="current_page_item" <? } ?> onclick="javascript:menu.changeMenu(this.id);">
                <a href="<?=$menu['href']?>"><?=$menu['titulo']?><p><?=$menu['subTitulo']?></p></a>
            </li>
            <? } ?>
        </ul>
    </div>            
</div>