<?php if(isset(self::$arrMenuOpts)){ ?>
    <div id="menuVerticalTop"><br/></div>
    <ul id="itemBtn">
        <?
            $controller = \Application::getController();
            foreach(self::$arrMenuOpts as $id=>$textoMenu) {
                $link       = '/'.\LoadConfig::root().'/'.$controller.'/';                
                $link       .= ($id == 'index')?'':$id;                
                $li .= "<li><a href='{$link}'>{$textoMenu}</a></li>";
            }
            echo $li;
        ?>         
    </ul>
    <div id="menuVerticalBottom"><br/></div>
<?php } ?>