<div class="top">
    <div class="container nav-wrap">
        <ul class="group" id="top-menu">
            <? foreach(self::$arrMenuOpts as $id => $menu){ ?>
            <li id="<?=$id?>" <? if($menu['ativo'] === TRUE){ ?> class="current_page_item" <? } ?> onclick="javascript:menu.changeMenu(this.id);">
                <a href="<?=$menu['href']?>"><?=$menu['titulo']?><p><?=$menu['subTitulo']?></p></a>
            </li>
            <? } ?>
        </ul>
    </div>            
</div>