<script type="text/javascript">
    function iniciaGraficoTop10 () {
        var chart;
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'grafico_top10_barras',
                    type: 'column',
                    height: 600,
                    margin: [0, 0, 0, 0],
                    spacingBottom: 5,
                    spacingTop: 5,
                    spacingLeft: 5,
                    spacingRight: 5
                },
                title: {
                    text: 'Histórico de TOP 10'
                },
                xAxis: {
                    categories: ['TOP 10']
                },
                yAxis: {
                    min: 0,
                    labels: {
                        enabled: false
                    },
                    title: {
                        text: ''
                    },
                    stackLabels: {
                        enabled: true,
                        style: {
                            fontWeight: 'bold',
                            color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                        },
                        formatter: function() {
                            return this.stack;
                        }
                    }
                },
                legend: {
                    enabled: false
                },
                tooltip: {
                    enabled: false
                },
                plotOptions: {
                    column: {
                        stacking: 'normal',
                        dataLabels: {
                            enabled: true,
                            color: '#000',
                            formatter: function() {
                                return this.series.name;
                            }
                        }
                    }
                },
                series: [
                <? foreach (self::$chartData->data as $row) { ?>
                        {
                            name: '<?=$row->POS_1;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_1]?>',
                            groupPadding: 0
                        },
                        
                        {
                            name: '<?=$row->POS_2;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_2]?>',
                            groupPadding: 0
                        },                
                        
                        {
                            name: '<?=$row->POS_3;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_3]?>',
                            groupPadding: 0
                        },                
                        
                        {
                            name: '<?=$row->POS_4;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_4]?>',
                            groupPadding: 0
                        },                
                        
                        {
                            name: '<?=$row->POS_5;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_5]?>',
                            groupPadding: 0
                        },                
                        
                        {
                            name: '<?=$row->POS_6;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_6]?>',
                            groupPadding: 0
                        },                
                        
                        {
                            name: '<?=$row->POS_7;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_7]?>',
                            groupPadding: 0
                        },                
                        
                        {
                            name: '<?=$row->POS_8;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_8]?>',
                            groupPadding: 0
                        },                
                        
                        {
                            name: '<?=$row->POS_9;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_9]?>',
                            groupPadding: 0
                        },                
                        
                        {
                            name: '<?=$row->POS_10;?>',
                            data: [20],
                            stack: '<?=\sys\classes\util\Date::formatDate($row->DATA_LOG, "DD/MM")?>',
                            color: '#<?=self::$chartData->colors[$row->POS_10]?>',
                            groupPadding: 0
                        },                
                <? } ?>
                ]
            });
            
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'grafico_top10_freq',
                    type: 'column',
                    margin: [50, 50, 100, 80]
                },
                title: {
                    text: 'Questões mais utilizadas'
                },
                xAxis: {
                    categories: ['Questões']
                },
                yAxis: {
                    min: 0,
                    max: 100,
                    title: {
                        text: 'Frequência %'
                    },
                    stackLabels: {
                        enabled: true,
                        style: {
                            fontWeight: 'bold',
                            color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                        },
                        formatter: function() {
                            return this.stack;
                        }
                    }
                },
                legend: {
                    enabled: false
                },
                tooltip: {
                    enabled: false
                },
                plotOptions: {
                    column: {
                        stacking: 'normal',
                        dataLabels: {
                            enabled: true,
                            color: '#000',
                            formatter: function() {
                                return this.series.name;
                            }
                        }
                    }
                },
                series: [
                    <? foreach (self::$chartData->top as $top){ ?>
                    {
                        name: '<?=$top['questao']?>',
                        data: [<?=$top['perc']?>],
                        color: '#<?=self::$chartData->colors[$top['questao']]?>',
                        stack: '<?=$top['questao']?>',
                        dataLabels: {
                            enabled: true,
                            align: 'center',
                            formatter: function() {
                                return this.y + "%";
                            },
                            style: {
                                fontWeight: 'bold'
                            }
                        }
                    },
                    <? } ?>
                ]
            });
            
//            chart = new Highcharts.Chart({
//                chart: {
//                    renderTo: 'grafico_top10_pizza',
//                    plotBackgroundColor: null,
//                    plotBorderWidth: null,
//                    plotShadow: false
//                },
//                title: {
//                    text: 'Questões mais utilizadas'
//                },
//                tooltip: {
//                    pointFormat: '{series.name}: <b>{point.percentage}%</b>',
//                    percentageDecimals: 1
//                },
//                plotOptions: {
//                    pie: {
//                        allowPointSelect: true,
//                        cursor: 'pointer',
//                        dataLabels: {
//                            enabled: true,
//                            color: '#000000',
//                            connectorColor: '#000000',
//                            formatter: function() {
//                                return '<b>'+ this.point.name +'</b>: '+ this.point.y +' %';
//                            }
//                        }
//                    }
//                },
//                series: [{
//                    type: 'pie',
//                    name: 'Percentagem',
//                    data: [
//                        <? foreach (self::$chartData->top as $top){ ?>
//                        {
//                            name: '<?=$top['questao']?>',
//                            y: parseFloat('<?=$top['perc']?>'),
//                            color: '#<?=self::$chartData->colors[$top['questao']]?>'
//                        },
//                        <? } ?>
//                    ]
//                }]
//            });
        }
</script>
<div id="grafico_top10_barras" style="width:85%;"></div>
<div id="grafico_top10_freq" style="width:85%;"></div>
